# Site settings

paginate: 10 # pagination based on number of posts
paginate_path: "/blog/page:num"

title: Liberis Labs
email: your-email@domain.com
description: ># At Liberis Labs we are building
 a cutting edge ecosystem that enables
 small businesses to gain easy access to finance.
baseurl: ""
url: "http://liberislabs.com"

disqus: 
twitter_username: LiberisLabs
github_username:  LiberisLabs
google_tag_manager: 

liberis_url: https://www.liberis.co.uk/?utm_source=liberis-labs&utm_medium=about-us
blenheim_chalcot_url: http://www.blenheimchalcot.com/?utm_source=liberis-labs&utm_medium=about-us

# Build settings
highlighter: pygments
markdown: redcarpet
encoding: utf-8
exclude: [semantic/node_modules/]

pageNumbers: [1,2,3,4,5]
array: []