# Site settings
title: Liberis Labs
email: your-email@domain.com
description: ># At Liberis Labs we are building
 a cutting edge ecosystem that enables
 small businesses to gain easy access to finance.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://liberislabs.com"
disqus: 
twitter_username: LiberisLabs
github_username:  LiberisLabs
google_tag_manager: 

# Build settings
highlighter: pygments
markdown: redcarpet
encoding: utf-8
exclude: [semantic/node_modules/]